from dataclasses import dataclass
from typing import Literal, get_args

RoutingAction = Literal["rag", "tool", "customer_service"]
ROUTING_ACTIONS = get_args(RoutingAction)

CustomerServiceDepartment = Literal[
    "general",
    "accounts",
    "cards",
    "transfers",
    "payments",
    "billing",
    "complaints",
    "fraud",
    "technical_support",
    "sales",
    "other",
]
CUSTOMER_SERVICE_DEPARTMENTS = get_args(CustomerServiceDepartment)


@dataclass(frozen=True)
class AIResponse:
    """Carries the structured response generated by the LLM and an optional language code."""
    action: RoutingAction
    department: CustomerServiceDepartment | None
    reason: str
    message: str
    language: str | None = None
