from dataclasses import dataclass

@dataclass(frozen=True)
class AIResponse:
    """Carries the response text generated by the LLM and an optional language code."""
    text: str
    language: str | None = None
