from dataclasses import dataclass
from typing import Literal

@dataclass(frozen=True)
class AIResponse:
    """Carries the structured response generated by the LLM and an optional language code."""
    action: Literal["retrieval", "tool", "human"]
    reason: str
    message: str
    language: str | None = None
