from pydantic import BaseModel, ConfigDict
from app.rag.models.status import RagStatus
from app.retrieval.models.search_result import SearchResult


class RagResponse(BaseModel):
    """
    Holds the final response details generated by the RAG pipeline.
    """
    model_config = ConfigDict(frozen=True)

    # The generated text answer from the LLM (or the fallback message).
    answer: str

    # The final prompt string sent to the LLM (empty string on INSUFFICIENT_CONTEXT).
    prompt: str

    # The list of SearchResults used (or evaluated) by this pipeline run.
    retrieved_documents: list[SearchResult]

    # Categorical outcome of the pipeline run.
    status: RagStatus = RagStatus.SUCCESS
