from pydantic import BaseModel, ConfigDict
from app.retrieval.models.search_result import SearchResult


class RagResponse(BaseModel):
    """
    Holds the final response details generated by the RAG pipeline.
    """
    model_config = ConfigDict(frozen=True)

    # The generated text answer from the LLM.
    answer: str

    # The final prompt string sent to the LLM (for debugging and iteration).
    prompt: str

    # The list of SearchResults used to construct the context for this query.
    retrieved_documents: list[SearchResult]
