from pydantic import BaseModel, ConfigDict
from app.rag.models.status import RagStatus
from app.retrieval.models.search_result import SearchResult


class ChunkDebugInfo(BaseModel):
    """Debug info for a single retrieved chunk."""
    model_config = ConfigDict(frozen=True)

    id: str
    product_name: str
    section: str
    score: float


class RagDebugInfo(BaseModel):
    """
    Detailed operational metrics and debug data for a single RAG request.
    Populated only when RAG_DEBUG setting or debug flag is enabled.
    """
    model_config = ConfigDict(frozen=True)

    original_query: str
    normalized_query: str
    retrieval_scores: list[float]
    retrieved_chunks: list[ChunkDebugInfo]
    final_context: str
    prompt_length_chars: int
    latencies_ms: dict[str, float]
    detection_reason: str
    has_context: bool


class RagResponse(BaseModel):
    """
    Holds the final response details generated by the RAG pipeline.
    """
    model_config = ConfigDict(frozen=True)

    # The generated text answer from the LLM (or the fallback message).
    answer: str

    # The final prompt string sent to the LLM (empty string on INSUFFICIENT_CONTEXT).
    prompt: str

    # The list of SearchResults used (or evaluated) by this pipeline run.
    retrieved_documents: list[SearchResult]

    # Categorical outcome of the pipeline run.
    status: RagStatus = RagStatus.SUCCESS

    # Optional debug metrics — populated only when DEBUG mode is enabled.
    debug_info: RagDebugInfo | None = None
